//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGFPortal.DataSetSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class shpc_bat
    {
        public string site { get; set; }
        public string kind { get; set; }
        public string shp_nbr { get; set; }
        public string shp_seq { get; set; }
        public string pre_shp_nbr { get; set; }
        public string pre_shp_seq { get; set; }
        public string ord_nbr { get; set; }
        public string ord_seq { get; set; }
        public string ord_rank { get; set; }
        public string doc_ctl { get; set; }
        public string rs_type { get; set; }
        public string item_no { get; set; }
        public string stockroom { get; set; }
        public string stockroom_to { get; set; }
        public string lot_nbr { get; set; }
        public string cus_item_name { get; set; }
        public string sales_um { get; set; }
        public string pack_unit { get; set; }
        public Nullable<decimal> sale_qty { get; set; }
        public Nullable<decimal> shp_qty { get; set; }
        public Nullable<decimal> rtn_qty { get; set; }
        public Nullable<decimal> aux_qty { get; set; }
        public Nullable<decimal> pack_qty { get; set; }
        public Nullable<decimal> inner_qty { get; set; }
        public Nullable<decimal> std_price { get; set; }
        public Nullable<decimal> sale_price { get; set; }
        public Nullable<decimal> shp_amt { get; set; }
        public Nullable<decimal> base_amt { get; set; }
        public Nullable<decimal> ship_cost { get; set; }
        public Nullable<decimal> other_expse { get; set; }
        public Nullable<decimal> discount_rate { get; set; }
        public Nullable<decimal> box_qty { get; set; }
        public Nullable<decimal> net_weight { get; set; }
        public Nullable<decimal> gross_weight { get; set; }
        public Nullable<decimal> cuft_size { get; set; }
        public string invoice_nbr { get; set; }
        public string reason { get; set; }
        public string shp_whence { get; set; }
        public string remark150 { get; set; }
        public Nullable<decimal> modify_count { get; set; }
        public string detail_status { get; set; }
        public string posted_ivc { get; set; }
        public string posted_sal { get; set; }
        public string posted_inv { get; set; }
        public Nullable<System.DateTime> post_inv_date { get; set; }
        public string protect_yn { get; set; }
        public string filter_creator { get; set; }
        public string filter_dept { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string modifier { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string cust_po_nbr { get; set; }
        public Nullable<decimal> commiss_amount { get; set; }
        public Nullable<decimal> base_commiss_amount { get; set; }
        public Nullable<decimal> add_reduce_item { get; set; }
    }
}
