#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGFPortal.資料庫連線
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GGF")]
	public partial class GGFDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void InsertGGFRequestSam(GGFRequestSam instance);
    partial void UpdateGGFRequestSam(GGFRequestSam instance);
    partial void DeleteGGFRequestSam(GGFRequestSam instance);
    partial void InsertGGFRequestMark(GGFRequestMark instance);
    partial void UpdateGGFRequestMark(GGFRequestMark instance);
    partial void DeleteGGFRequestMark(GGFRequestMark instance);
    #endregion
		
		public GGFDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GGFConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GGFDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GGFDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GGFDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GGFDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GGFRequestSam> GGFRequestSam
		{
			get
			{
				return this.GetTable<GGFRequestSam>();
			}
		}
		
		public System.Data.Linq.Table<GGFRequestMark> GGFRequestMark
		{
			get
			{
				return this.GetTable<GGFRequestMark>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GGFRequestSam")]
	public partial class GGFRequestSam : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _uid;
		
		private string _site;
		
		private string _sam_nbr;
		
		private string _SampleType;
		
		private string _SampleUser;
		
		private string _SampleNo;
		
		private decimal _Qty;
		
		private string _Remark;
		
		private string _SampleCreatDate;
		
		private System.DateTime _CreatDate;
		
		private int _Flag;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private string _馬克;
		
		private string _修改馬克;
		
		private string _馬克完成日;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(int value);
    partial void OnuidChanged();
    partial void OnsiteChanging(string value);
    partial void OnsiteChanged();
    partial void Onsam_nbrChanging(string value);
    partial void Onsam_nbrChanged();
    partial void OnSampleTypeChanging(string value);
    partial void OnSampleTypeChanged();
    partial void OnSampleUserChanging(string value);
    partial void OnSampleUserChanged();
    partial void OnSampleNoChanging(string value);
    partial void OnSampleNoChanged();
    partial void OnQtyChanging(decimal value);
    partial void OnQtyChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnSampleCreatDateChanging(string value);
    partial void OnSampleCreatDateChanged();
    partial void OnCreatDateChanging(System.DateTime value);
    partial void OnCreatDateChanged();
    partial void OnFlagChanging(int value);
    partial void OnFlagChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    partial void On馬克Changing(string value);
    partial void On馬克Changed();
    partial void On修改馬克Changing(string value);
    partial void On修改馬克Changed();
    partial void On馬克完成日Changing(string value);
    partial void On馬克完成日Changed();
    #endregion
		
		public GGFRequestSam()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site", DbType="NVarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string site
		{
			get
			{
				return this._site;
			}
			set
			{
				if ((this._site != value))
				{
					this.OnsiteChanging(value);
					this.SendPropertyChanging();
					this._site = value;
					this.SendPropertyChanged("site");
					this.OnsiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sam_nbr", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string sam_nbr
		{
			get
			{
				return this._sam_nbr;
			}
			set
			{
				if ((this._sam_nbr != value))
				{
					this.Onsam_nbrChanging(value);
					this.SendPropertyChanging();
					this._sam_nbr = value;
					this.SendPropertyChanged("sam_nbr");
					this.Onsam_nbrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SampleType", DbType="NVarChar(10)")]
		public string SampleType
		{
			get
			{
				return this._SampleType;
			}
			set
			{
				if ((this._SampleType != value))
				{
					this.OnSampleTypeChanging(value);
					this.SendPropertyChanging();
					this._SampleType = value;
					this.SendPropertyChanged("SampleType");
					this.OnSampleTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SampleUser", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string SampleUser
		{
			get
			{
				return this._SampleUser;
			}
			set
			{
				if ((this._SampleUser != value))
				{
					this.OnSampleUserChanging(value);
					this.SendPropertyChanging();
					this._SampleUser = value;
					this.SendPropertyChanged("SampleUser");
					this.OnSampleUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SampleNo", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string SampleNo
		{
			get
			{
				return this._SampleNo;
			}
			set
			{
				if ((this._SampleNo != value))
				{
					this.OnSampleNoChanging(value);
					this.SendPropertyChanging();
					this._SampleNo = value;
					this.SendPropertyChanged("SampleNo");
					this.OnSampleNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qty", DbType="Decimal(18,1) NOT NULL")]
		public decimal Qty
		{
			get
			{
				return this._Qty;
			}
			set
			{
				if ((this._Qty != value))
				{
					this.OnQtyChanging(value);
					this.SendPropertyChanging();
					this._Qty = value;
					this.SendPropertyChanged("Qty");
					this.OnQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(100)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SampleCreatDate", DbType="NVarChar(8)")]
		public string SampleCreatDate
		{
			get
			{
				return this._SampleCreatDate;
			}
			set
			{
				if ((this._SampleCreatDate != value))
				{
					this.OnSampleCreatDateChanging(value);
					this.SendPropertyChanging();
					this._SampleCreatDate = value;
					this.SendPropertyChanged("SampleCreatDate");
					this.OnSampleCreatDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreatDate
		{
			get
			{
				return this._CreatDate;
			}
			set
			{
				if ((this._CreatDate != value))
				{
					this.OnCreatDateChanging(value);
					this.SendPropertyChanging();
					this._CreatDate = value;
					this.SendPropertyChanged("CreatDate");
					this.OnCreatDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag", DbType="Int NOT NULL")]
		public int Flag
		{
			get
			{
				return this._Flag;
			}
			set
			{
				if ((this._Flag != value))
				{
					this.OnFlagChanging(value);
					this.SendPropertyChanging();
					this._Flag = value;
					this.SendPropertyChanged("Flag");
					this.OnFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this.OnModifyDateChanging(value);
					this.SendPropertyChanging();
					this._ModifyDate = value;
					this.SendPropertyChanged("ModifyDate");
					this.OnModifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_馬克", DbType="NVarChar(30)")]
		public string 馬克
		{
			get
			{
				return this._馬克;
			}
			set
			{
				if ((this._馬克 != value))
				{
					this.On馬克Changing(value);
					this.SendPropertyChanging();
					this._馬克 = value;
					this.SendPropertyChanged("馬克");
					this.On馬克Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_修改馬克", DbType="NVarChar(30)")]
		public string 修改馬克
		{
			get
			{
				return this._修改馬克;
			}
			set
			{
				if ((this._修改馬克 != value))
				{
					this.On修改馬克Changing(value);
					this.SendPropertyChanging();
					this._修改馬克 = value;
					this.SendPropertyChanged("修改馬克");
					this.On修改馬克Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_馬克完成日", DbType="NVarChar(8)")]
		public string 馬克完成日
		{
			get
			{
				return this._馬克完成日;
			}
			set
			{
				if ((this._馬克完成日 != value))
				{
					this.On馬克完成日Changing(value);
					this.SendPropertyChanging();
					this._馬克完成日 = value;
					this.SendPropertyChanged("馬克完成日");
					this.On馬克完成日Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GGFRequestMark")]
	public partial class GGFRequestMark : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _uid;
		
		private string _修改人員;
		
		private string _工號;
		
		private string _處理類別;
		
		private System.DateTime _建立日期;
		
		private int _狀態;
		
		private string _修改日期;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnuidChanging(int value);
    partial void OnuidChanged();
    partial void On修改人員Changing(string value);
    partial void On修改人員Changed();
    partial void On工號Changing(string value);
    partial void On工號Changed();
    partial void On處理類別Changing(string value);
    partial void On處理類別Changed();
    partial void On建立日期Changing(System.DateTime value);
    partial void On建立日期Changed();
    partial void On狀態Changing(int value);
    partial void On狀態Changed();
    partial void On修改日期Changing(string value);
    partial void On修改日期Changed();
    #endregion
		
		public GGFRequestMark()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_修改人員", DbType="NVarChar(30)")]
		public string 修改人員
		{
			get
			{
				return this._修改人員;
			}
			set
			{
				if ((this._修改人員 != value))
				{
					this.On修改人員Changing(value);
					this.SendPropertyChanging();
					this._修改人員 = value;
					this.SendPropertyChanged("修改人員");
					this.On修改人員Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_工號", DbType="NVarChar(8)")]
		public string 工號
		{
			get
			{
				return this._工號;
			}
			set
			{
				if ((this._工號 != value))
				{
					this.On工號Changing(value);
					this.SendPropertyChanging();
					this._工號 = value;
					this.SendPropertyChanged("工號");
					this.On工號Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_處理類別", DbType="NVarChar(10)")]
		public string 處理類別
		{
			get
			{
				return this._處理類別;
			}
			set
			{
				if ((this._處理類別 != value))
				{
					this.On處理類別Changing(value);
					this.SendPropertyChanging();
					this._處理類別 = value;
					this.SendPropertyChanged("處理類別");
					this.On處理類別Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_建立日期", DbType="DateTime NOT NULL")]
		public System.DateTime 建立日期
		{
			get
			{
				return this._建立日期;
			}
			set
			{
				if ((this._建立日期 != value))
				{
					this.On建立日期Changing(value);
					this.SendPropertyChanging();
					this._建立日期 = value;
					this.SendPropertyChanged("建立日期");
					this.On建立日期Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_狀態", DbType="Int NOT NULL")]
		public int 狀態
		{
			get
			{
				return this._狀態;
			}
			set
			{
				if ((this._狀態 != value))
				{
					this.On狀態Changing(value);
					this.SendPropertyChanging();
					this._狀態 = value;
					this.SendPropertyChanged("狀態");
					this.On狀態Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_修改日期", DbType="NChar(10)")]
		public string 修改日期
		{
			get
			{
				return this._修改日期;
			}
			set
			{
				if ((this._修改日期 != value))
				{
					this.On修改日期Changing(value);
					this.SendPropertyChanging();
					this._修改日期 = value;
					this.SendPropertyChanged("修改日期");
					this.On修改日期Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
